//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldDBClient.WorldServ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictField;
        
        private int PopulationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string District {
            get {
                return this.DistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictField, value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Population {
            get {
                return this.PopulationField;
            }
            set {
                if ((this.PopulationField.Equals(value) != true)) {
                    this.PopulationField = value;
                    this.RaisePropertyChanged("Population");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContinentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        private float SurfaceAreaField;
        
        private long PopulationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Continent {
            get {
                return this.ContinentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContinentField, value) != true)) {
                    this.ContinentField = value;
                    this.RaisePropertyChanged("Continent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public float SurfaceArea {
            get {
                return this.SurfaceAreaField;
            }
            set {
                if ((this.SurfaceAreaField.Equals(value) != true)) {
                    this.SurfaceAreaField = value;
                    this.RaisePropertyChanged("SurfaceArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public long Population {
            get {
                return this.PopulationField;
            }
            set {
                if ((this.PopulationField.Equals(value) != true)) {
                    this.PopulationField = value;
                    this.RaisePropertyChanged("Population");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorldServ.WorldDBServSoap")]
    public interface WorldDBServSoap {
        
        // CODEGEN: Generating message contract since element name getAllCitiesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllCities", ReplyAction="*")]
        WorldDBClient.WorldServ.getAllCitiesResponse getAllCities(WorldDBClient.WorldServ.getAllCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllCities", ReplyAction="*")]
        System.Threading.Tasks.Task<WorldDBClient.WorldServ.getAllCitiesResponse> getAllCitiesAsync(WorldDBClient.WorldServ.getAllCitiesRequest request);
        
        // CODEGEN: Generating message contract since element name countryCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountryByCode", ReplyAction="*")]
        WorldDBClient.WorldServ.GetCountryByCodeResponse GetCountryByCode(WorldDBClient.WorldServ.GetCountryByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountryByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<WorldDBClient.WorldServ.GetCountryByCodeResponse> GetCountryByCodeAsync(WorldDBClient.WorldServ.GetCountryByCodeRequest request);
        
        // CODEGEN: Generating message contract since element name cityName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityByName", ReplyAction="*")]
        WorldDBClient.WorldServ.GetCityByNameResponse GetCityByName(WorldDBClient.WorldServ.GetCityByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityByName", ReplyAction="*")]
        System.Threading.Tasks.Task<WorldDBClient.WorldServ.GetCityByNameResponse> GetCityByNameAsync(WorldDBClient.WorldServ.GetCityByNameRequest request);
        
        // CODEGEN: Generating message contract since element name countryCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCitiesByCountry", ReplyAction="*")]
        WorldDBClient.WorldServ.GetCitiesByCountryResponse GetCitiesByCountry(WorldDBClient.WorldServ.GetCitiesByCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCitiesByCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<WorldDBClient.WorldServ.GetCitiesByCountryResponse> GetCitiesByCountryAsync(WorldDBClient.WorldServ.GetCitiesByCountryRequest request);
        
        // CODEGEN: Generating message contract since element name GetCountriesByPopulationResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountriesByPopulation", ReplyAction="*")]
        WorldDBClient.WorldServ.GetCountriesByPopulationResponse GetCountriesByPopulation(WorldDBClient.WorldServ.GetCountriesByPopulationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountriesByPopulation", ReplyAction="*")]
        System.Threading.Tasks.Task<WorldDBClient.WorldServ.GetCountriesByPopulationResponse> GetCountriesByPopulationAsync(WorldDBClient.WorldServ.GetCountriesByPopulationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllCitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllCities", Namespace="http://tempuri.org/", Order=0)]
        public WorldDBClient.WorldServ.getAllCitiesRequestBody Body;
        
        public getAllCitiesRequest() {
        }
        
        public getAllCitiesRequest(WorldDBClient.WorldServ.getAllCitiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllCitiesRequestBody {
        
        public getAllCitiesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllCitiesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WorldDBClient.WorldServ.getAllCitiesResponseBody Body;
        
        public getAllCitiesResponse() {
        }
        
        public getAllCitiesResponse(WorldDBClient.WorldServ.getAllCitiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllCitiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WorldDBClient.WorldServ.City[] getAllCitiesResult;
        
        public getAllCitiesResponseBody() {
        }
        
        public getAllCitiesResponseBody(WorldDBClient.WorldServ.City[] getAllCitiesResult) {
            this.getAllCitiesResult = getAllCitiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCode", Namespace="http://tempuri.org/", Order=0)]
        public WorldDBClient.WorldServ.GetCountryByCodeRequestBody Body;
        
        public GetCountryByCodeRequest() {
        }
        
        public GetCountryByCodeRequest(WorldDBClient.WorldServ.GetCountryByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string countryCode;
        
        public GetCountryByCodeRequestBody() {
        }
        
        public GetCountryByCodeRequestBody(string countryCode) {
            this.countryCode = countryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WorldDBClient.WorldServ.GetCountryByCodeResponseBody Body;
        
        public GetCountryByCodeResponse() {
        }
        
        public GetCountryByCodeResponse(WorldDBClient.WorldServ.GetCountryByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WorldDBClient.WorldServ.Country GetCountryByCodeResult;
        
        public GetCountryByCodeResponseBody() {
        }
        
        public GetCountryByCodeResponseBody(WorldDBClient.WorldServ.Country GetCountryByCodeResult) {
            this.GetCountryByCodeResult = GetCountryByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityByName", Namespace="http://tempuri.org/", Order=0)]
        public WorldDBClient.WorldServ.GetCityByNameRequestBody Body;
        
        public GetCityByNameRequest() {
        }
        
        public GetCityByNameRequest(WorldDBClient.WorldServ.GetCityByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCityByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cityName;
        
        public GetCityByNameRequestBody() {
        }
        
        public GetCityByNameRequestBody(string cityName) {
            this.cityName = cityName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public WorldDBClient.WorldServ.GetCityByNameResponseBody Body;
        
        public GetCityByNameResponse() {
        }
        
        public GetCityByNameResponse(WorldDBClient.WorldServ.GetCityByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCityByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WorldDBClient.WorldServ.City GetCityByNameResult;
        
        public GetCityByNameResponseBody() {
        }
        
        public GetCityByNameResponseBody(WorldDBClient.WorldServ.City GetCityByNameResult) {
            this.GetCityByNameResult = GetCityByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesByCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesByCountry", Namespace="http://tempuri.org/", Order=0)]
        public WorldDBClient.WorldServ.GetCitiesByCountryRequestBody Body;
        
        public GetCitiesByCountryRequest() {
        }
        
        public GetCitiesByCountryRequest(WorldDBClient.WorldServ.GetCitiesByCountryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesByCountryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string countryCode;
        
        public GetCitiesByCountryRequestBody() {
        }
        
        public GetCitiesByCountryRequestBody(string countryCode) {
            this.countryCode = countryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesByCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesByCountryResponse", Namespace="http://tempuri.org/", Order=0)]
        public WorldDBClient.WorldServ.GetCitiesByCountryResponseBody Body;
        
        public GetCitiesByCountryResponse() {
        }
        
        public GetCitiesByCountryResponse(WorldDBClient.WorldServ.GetCitiesByCountryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesByCountryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WorldDBClient.WorldServ.City[] GetCitiesByCountryResult;
        
        public GetCitiesByCountryResponseBody() {
        }
        
        public GetCitiesByCountryResponseBody(WorldDBClient.WorldServ.City[] GetCitiesByCountryResult) {
            this.GetCitiesByCountryResult = GetCitiesByCountryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesByPopulationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountriesByPopulation", Namespace="http://tempuri.org/", Order=0)]
        public WorldDBClient.WorldServ.GetCountriesByPopulationRequestBody Body;
        
        public GetCountriesByPopulationRequest() {
        }
        
        public GetCountriesByPopulationRequest(WorldDBClient.WorldServ.GetCountriesByPopulationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountriesByPopulationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long populationThreshold;
        
        public GetCountriesByPopulationRequestBody() {
        }
        
        public GetCountriesByPopulationRequestBody(long populationThreshold) {
            this.populationThreshold = populationThreshold;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesByPopulationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountriesByPopulationResponse", Namespace="http://tempuri.org/", Order=0)]
        public WorldDBClient.WorldServ.GetCountriesByPopulationResponseBody Body;
        
        public GetCountriesByPopulationResponse() {
        }
        
        public GetCountriesByPopulationResponse(WorldDBClient.WorldServ.GetCountriesByPopulationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountriesByPopulationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WorldDBClient.WorldServ.Country[] GetCountriesByPopulationResult;
        
        public GetCountriesByPopulationResponseBody() {
        }
        
        public GetCountriesByPopulationResponseBody(WorldDBClient.WorldServ.Country[] GetCountriesByPopulationResult) {
            this.GetCountriesByPopulationResult = GetCountriesByPopulationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WorldDBServSoapChannel : WorldDBClient.WorldServ.WorldDBServSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorldDBServSoapClient : System.ServiceModel.ClientBase<WorldDBClient.WorldServ.WorldDBServSoap>, WorldDBClient.WorldServ.WorldDBServSoap {
        
        public WorldDBServSoapClient() {
        }
        
        public WorldDBServSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorldDBServSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorldDBServSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorldDBServSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WorldDBClient.WorldServ.getAllCitiesResponse WorldDBClient.WorldServ.WorldDBServSoap.getAllCities(WorldDBClient.WorldServ.getAllCitiesRequest request) {
            return base.Channel.getAllCities(request);
        }
        
        public WorldDBClient.WorldServ.City[] getAllCities() {
            WorldDBClient.WorldServ.getAllCitiesRequest inValue = new WorldDBClient.WorldServ.getAllCitiesRequest();
            inValue.Body = new WorldDBClient.WorldServ.getAllCitiesRequestBody();
            WorldDBClient.WorldServ.getAllCitiesResponse retVal = ((WorldDBClient.WorldServ.WorldDBServSoap)(this)).getAllCities(inValue);
            return retVal.Body.getAllCitiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorldDBClient.WorldServ.getAllCitiesResponse> WorldDBClient.WorldServ.WorldDBServSoap.getAllCitiesAsync(WorldDBClient.WorldServ.getAllCitiesRequest request) {
            return base.Channel.getAllCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorldDBClient.WorldServ.getAllCitiesResponse> getAllCitiesAsync() {
            WorldDBClient.WorldServ.getAllCitiesRequest inValue = new WorldDBClient.WorldServ.getAllCitiesRequest();
            inValue.Body = new WorldDBClient.WorldServ.getAllCitiesRequestBody();
            return ((WorldDBClient.WorldServ.WorldDBServSoap)(this)).getAllCitiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WorldDBClient.WorldServ.GetCountryByCodeResponse WorldDBClient.WorldServ.WorldDBServSoap.GetCountryByCode(WorldDBClient.WorldServ.GetCountryByCodeRequest request) {
            return base.Channel.GetCountryByCode(request);
        }
        
        public WorldDBClient.WorldServ.Country GetCountryByCode(string countryCode) {
            WorldDBClient.WorldServ.GetCountryByCodeRequest inValue = new WorldDBClient.WorldServ.GetCountryByCodeRequest();
            inValue.Body = new WorldDBClient.WorldServ.GetCountryByCodeRequestBody();
            inValue.Body.countryCode = countryCode;
            WorldDBClient.WorldServ.GetCountryByCodeResponse retVal = ((WorldDBClient.WorldServ.WorldDBServSoap)(this)).GetCountryByCode(inValue);
            return retVal.Body.GetCountryByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorldDBClient.WorldServ.GetCountryByCodeResponse> WorldDBClient.WorldServ.WorldDBServSoap.GetCountryByCodeAsync(WorldDBClient.WorldServ.GetCountryByCodeRequest request) {
            return base.Channel.GetCountryByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorldDBClient.WorldServ.GetCountryByCodeResponse> GetCountryByCodeAsync(string countryCode) {
            WorldDBClient.WorldServ.GetCountryByCodeRequest inValue = new WorldDBClient.WorldServ.GetCountryByCodeRequest();
            inValue.Body = new WorldDBClient.WorldServ.GetCountryByCodeRequestBody();
            inValue.Body.countryCode = countryCode;
            return ((WorldDBClient.WorldServ.WorldDBServSoap)(this)).GetCountryByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WorldDBClient.WorldServ.GetCityByNameResponse WorldDBClient.WorldServ.WorldDBServSoap.GetCityByName(WorldDBClient.WorldServ.GetCityByNameRequest request) {
            return base.Channel.GetCityByName(request);
        }
        
        public WorldDBClient.WorldServ.City GetCityByName(string cityName) {
            WorldDBClient.WorldServ.GetCityByNameRequest inValue = new WorldDBClient.WorldServ.GetCityByNameRequest();
            inValue.Body = new WorldDBClient.WorldServ.GetCityByNameRequestBody();
            inValue.Body.cityName = cityName;
            WorldDBClient.WorldServ.GetCityByNameResponse retVal = ((WorldDBClient.WorldServ.WorldDBServSoap)(this)).GetCityByName(inValue);
            return retVal.Body.GetCityByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorldDBClient.WorldServ.GetCityByNameResponse> WorldDBClient.WorldServ.WorldDBServSoap.GetCityByNameAsync(WorldDBClient.WorldServ.GetCityByNameRequest request) {
            return base.Channel.GetCityByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorldDBClient.WorldServ.GetCityByNameResponse> GetCityByNameAsync(string cityName) {
            WorldDBClient.WorldServ.GetCityByNameRequest inValue = new WorldDBClient.WorldServ.GetCityByNameRequest();
            inValue.Body = new WorldDBClient.WorldServ.GetCityByNameRequestBody();
            inValue.Body.cityName = cityName;
            return ((WorldDBClient.WorldServ.WorldDBServSoap)(this)).GetCityByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WorldDBClient.WorldServ.GetCitiesByCountryResponse WorldDBClient.WorldServ.WorldDBServSoap.GetCitiesByCountry(WorldDBClient.WorldServ.GetCitiesByCountryRequest request) {
            return base.Channel.GetCitiesByCountry(request);
        }
        
        public WorldDBClient.WorldServ.City[] GetCitiesByCountry(string countryCode) {
            WorldDBClient.WorldServ.GetCitiesByCountryRequest inValue = new WorldDBClient.WorldServ.GetCitiesByCountryRequest();
            inValue.Body = new WorldDBClient.WorldServ.GetCitiesByCountryRequestBody();
            inValue.Body.countryCode = countryCode;
            WorldDBClient.WorldServ.GetCitiesByCountryResponse retVal = ((WorldDBClient.WorldServ.WorldDBServSoap)(this)).GetCitiesByCountry(inValue);
            return retVal.Body.GetCitiesByCountryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorldDBClient.WorldServ.GetCitiesByCountryResponse> WorldDBClient.WorldServ.WorldDBServSoap.GetCitiesByCountryAsync(WorldDBClient.WorldServ.GetCitiesByCountryRequest request) {
            return base.Channel.GetCitiesByCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorldDBClient.WorldServ.GetCitiesByCountryResponse> GetCitiesByCountryAsync(string countryCode) {
            WorldDBClient.WorldServ.GetCitiesByCountryRequest inValue = new WorldDBClient.WorldServ.GetCitiesByCountryRequest();
            inValue.Body = new WorldDBClient.WorldServ.GetCitiesByCountryRequestBody();
            inValue.Body.countryCode = countryCode;
            return ((WorldDBClient.WorldServ.WorldDBServSoap)(this)).GetCitiesByCountryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WorldDBClient.WorldServ.GetCountriesByPopulationResponse WorldDBClient.WorldServ.WorldDBServSoap.GetCountriesByPopulation(WorldDBClient.WorldServ.GetCountriesByPopulationRequest request) {
            return base.Channel.GetCountriesByPopulation(request);
        }
        
        public WorldDBClient.WorldServ.Country[] GetCountriesByPopulation(long populationThreshold) {
            WorldDBClient.WorldServ.GetCountriesByPopulationRequest inValue = new WorldDBClient.WorldServ.GetCountriesByPopulationRequest();
            inValue.Body = new WorldDBClient.WorldServ.GetCountriesByPopulationRequestBody();
            inValue.Body.populationThreshold = populationThreshold;
            WorldDBClient.WorldServ.GetCountriesByPopulationResponse retVal = ((WorldDBClient.WorldServ.WorldDBServSoap)(this)).GetCountriesByPopulation(inValue);
            return retVal.Body.GetCountriesByPopulationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorldDBClient.WorldServ.GetCountriesByPopulationResponse> WorldDBClient.WorldServ.WorldDBServSoap.GetCountriesByPopulationAsync(WorldDBClient.WorldServ.GetCountriesByPopulationRequest request) {
            return base.Channel.GetCountriesByPopulationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorldDBClient.WorldServ.GetCountriesByPopulationResponse> GetCountriesByPopulationAsync(long populationThreshold) {
            WorldDBClient.WorldServ.GetCountriesByPopulationRequest inValue = new WorldDBClient.WorldServ.GetCountriesByPopulationRequest();
            inValue.Body = new WorldDBClient.WorldServ.GetCountriesByPopulationRequestBody();
            inValue.Body.populationThreshold = populationThreshold;
            return ((WorldDBClient.WorldServ.WorldDBServSoap)(this)).GetCountriesByPopulationAsync(inValue);
        }
    }
}
